spring.application.name=GreenVibe
spring.datasource.username=${MYSQL_DB_USERNAME}
spring.datasource.password=${MYSQL_DB_PASSWORD}
spring.datasource.url=jdbc:mysql://${MYSQL_DB_HOST:localhost}:${MYSQL_DB_PORT:3306}/${MYSQL_DB_NAME:greenvibe}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
cloudinary.cloud-name=${CLOUDINARY_USERNAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
# JWT Settings
application.security.jwt.secret-key=586E3272357538782F413F4428472B4B6250655368566D597133743677397A24
application.security.jwt.expiration=864000000

# Logging settings
logging.level.root=INFO
logging.level.com.app.greenvibe=INFO
logging.level.com.app.greenvibe.service=DEBUG
logging.level.com.app.greenvibe.controller=INFO
logging.level.com.app.greenvibe.security=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/greenvibe.log

